use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let resources_dir = manifest_dir.join("resources").join("bytecode");

    println!("cargo:rerun-if-changed={}", resources_dir.display());

    let mut versions = Vec::new();
    if let Ok(entries) = fs::read_dir(&resources_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            if let Some(version) = parse_version(&path) {
                versions.push(version);
            }
        }
    }

    versions.sort_unstable();
    versions.dedup();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("bytecode_formats.rs");
    let mut out_file = fs::File::create(&out_path).expect("create bytecode_formats.rs");

    writeln!(out_file, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(out_file, "pub fn available_versions() -> &'static [u32] {{").unwrap();
    writeln!(out_file, "    &[{}]", versions.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", ")).unwrap();
    writeln!(out_file, "}}").unwrap();

    writeln!(out_file, "pub fn format_json_for_version(version: u32) -> Option<&'static str> {{").unwrap();
    writeln!(out_file, "    match version {{").unwrap();
    for version in &versions {
        let file_name = format!("Bytecode{version}.json");
        let rel_path = Path::new("resources").join("bytecode").join(file_name);
        writeln!(
            out_file,
            "        {version} => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", \"{}\"))),",
            rel_path.display()
        )
        .unwrap();
    }
    writeln!(out_file, "        _ => None,").unwrap();
    writeln!(out_file, "    }}").unwrap();
    writeln!(out_file, "}}").unwrap();
}

fn parse_version(path: &Path) -> Option<u32> {
    let file_name = path.file_stem()?.to_str()?;
    if !file_name.starts_with("Bytecode") {
        return None;
    }
    file_name["Bytecode".len()..].parse::<u32>().ok()
}
