import sys
import os
import re

REMOVE_MODULE_NAMES = [
    "?", "parseChrome", "toExtendedError", "get ActivityIndicator", "get hairlineWidth", "composeStyles", 
    "cxxNativeAnimatedEnabled", "createJavaScriptFlagGetter", 
    "NativeReactNativeFeatureFlagsCxx", "get", "invariant", "genModule", 
    "_slicedToArray", "_arrayWithHoles", "_iterableToArrayLimit", 
    "_unsupportedIterableToArray", "_arrayLikeToArray", "_nonIterableRest", 
    "MessageQueue", "_classCallCheck", "_createClass", "toPropertyKey", 
    "toPrimitive", "_typeof", "beginAsyncEvent", "createStringifySafeWithLimits", 
    "defineLazyObjectProperty", "processAspectRatio", "processColorStops", 
    "processColor", "normalizeColor", "hslToRgb", "PlatformColor", 
    "getPositionFromCSSValue", "isBackgroundRepeatKeyword", 
    "parseBackgroundSizeCSSString", "parseBoxShadowString", "_getFilterAmount", 
    "processFontVariant", "_getKeyAndValueFromCSSTransform", 
    "processTransformOrigin", "sizesDiffer", "flattenStyle", "PixelRatio", 
    "Dimensions", "_isNativeReflectConstruct", "_possibleConstructorReturn", 
    "_assertThisInitialized", "_getPrototypeOf", "_get", "_superPropBase", 
    "_inherits", "_setPrototypeOf", "EventEmitter", "_classPrivateFieldBase", 
    "_classPrivateFieldKey", "DeviceInfo", "get Version", "PlatformConstants", 
    "View", "_objectWithoutProperties", "_objectWithoutPropertiesLoose", "noop", 
    "RCTView", "merge", "nullthrows", "getViewManagerConfig", 
    "createProxyWithCachedProperties", "unstable_hasComponent", "getConstants", 
    "UIManager", "matricesDiffer", "pointsDiffer", "insetsDiffer", 
    "processColorElement", "getDevServerURL", "SourceCode", "AssetSourceResolver", 
    "getUrlCacheBreaker", "accumulateDifferences", "createViewConfig", 
    "ConditionallyIgnoredEventHandlers", "codegenNativeCommands", "keys", 
    "ReactFabric", "describeBuiltInComponentFrame", 
    "setUpDefaltReactNativeEnvironment", "setUpDOM", "polyfillGlobal", 
    "DOMRectReadOnly", "getPlatformObjectClone", "createDOMRectList", 
    "createEntriesIterator", "createHTMLCollection", "createNodeList", 
    "getChildNodes", "NativeDOMCxx", "getInstanceHandle", 
    "createReactNativeDocumentInstanceHandle", 
    "createReactNativeDocumentElementInstanceHandle", "AndroidTextInput", 
    "warnForStyleProps", "getElementSibling", "restoreDeletedValuesInNestedArray", 
    "deepDiffer", "setUpPerformanceModern", "getMarkTimeForMeasure", 
    "_wrapNativeSuper", "_isNativeFunction", "_construct", "structuredCloneInternal", 
    "MemoryInfo", "ReactNativeStartupTiming", "NativePerformanceCxx", 
    "PerformanceEntry", "warnNoNativePerformance", "warnOnce", 
    "performanceEntryTypeToRaw", "_createNativeObserver2", "valuePromise", 
    "finally", "NativeMicrotasksCxx", "clearImmediate", "NativeIdleCallbacksCxx", 
    "_callTimer", "Timing", "toError", "queueMicrotask", "convertHermesStack", 
    "parse", "parseHermesStack", "ExceptionsManager", "hasNativeConstructor", 
    "Event", "getComposedPath", "dispatch", "dispatchTrustedEvent", "BlobManager", 
    "BlobModule", "register", "getEventHandlerAttributeMap", 
    "createPerformanceLogger", "byteLength", "NativeEventEmitter", 
    "binaryToBase64", 
    "getWrapper", 
    "Alert", "DialogManagerAndroid", "emptyCallback", "__fetchSegment", 
    "SegmentFetcher", "LogBox", "cancelHeadlessTask", "renderApplication", 
    "usePerformanceLogger", "jsxProd", "createRootTag", "coerceDisplayMode", 
    "getCachedComponentWithDisplayName", "DeviceEventManager", 
    "HeadlessJsTaskSupport", "setUpIntersectionObserver", "normalizeRootMargin", 
    "getTargetFromInstanceHandle", "NativeIntersectionObserverCxx", 
    "createIntersectionObserverEntry", "setUpMutationObserver", "MutationObserver", 
    "notifyMutationObservers", "NativeMutationObserverCxx", "createMutationRecord", 
    "get BatchedBridge", "deepFreezeAndThrowOnMutationInDev", 
    "legacySendAccessibilityEvent", "createPublicInstance", "peek", 
    "getExtendedError", "ProgressBarAndroid", "AndroidProgressBar", 
    "codegenNativeComponent", "requireNativeComponent", 
    "createReactNativeComponentClass", "RCTActivityIndicatorView", 
    "useTextPressability", "PressabilityDebugView", "usePressability", 
    "isActiveSignal", "SoundManager", "PressabilityPerformanceEventEmitter", 
    "isHoverEnabled", "createSquare", "_combineCallbacks", "Animation", 
    "shouldUseTurboAnimatedModule", "_assertNativeAnimatedModule", 
    "attachNativeEventImpl", "bezier", "_readOnlyError", "fromBouncinessAndSpeed", 
    "createAnimatedComponent", "addListenersToPropsValue", "useRefEffect", 
    "createCompositeKeyForProps", "isPublicInstance", "useMergeRefs", 
    "mockCompositeAnimation", "get VirtualizedList", "elementsThatOverlapOffsets", 
    "clamp", "infoLog", "ChildListCollection", "Info", "ListMetricsAggregator", 
    "ViewabilityHelper", "VirtualizedListCellContextProvider", "horizontalOrDefault", 
    "CellRenderMask", "areInputsEqual", "_queryCache", "asyncGeneratorStep", 
    "ImageLoader", "getImageSourcesFromImageProps", "convertObjectFitToResizeMode", 
    "unstable_getImageComponentDecorator", 
    "AnimatedScrollViewWithInvertedRefreshControl", "RCTRefreshControl", 
    "FrameRateLogger", "splitLayoutProps", "dismissKeyboard", "KeyboardImpl", 
    "configureNext", "KeyboardObserver", "processDecelerationRate", 
    "ScrollViewStickyHeader", "AndroidHorizontalScrollView", "RCTScrollContentView", 
    "AndroidHorizontalScrollContentView", "StatusBarManager", "AndroidDrawerLayout", 
    "InputAccessoryView", "RCTSafeAreaView", "useWindowDimensions", 
    "RCTInputAccessoryView", "AccessibilityInfo", "AccessibilityManager", 
    "LayoutConformance", "ModalManager", "RCTModalHostView", "I18nManager", 
    "Pressable", "useAndroidRippleForView", "returnsFalse", "AndroidSwitch", 
    "RCTSwitch", "InternalTextInput", "RCTSinglelineTextInputView", 
    "RCTMultilineTextInputView", "extractSingleTouch", "destructor", 
    "oneArgumentPooler", "TouchableWithoutFeedback", "defaultHiddenStyle", 
    "VirtualViewExperimental", "VirtualView", "useVirtualViewLogging", 
    "addChangeListener", "Appearance", "AppStateImpl", 
    "logError", "DevMenu", "DevSettings", 
    "DynamicColorIOS", "reject",
    "PermissionsAndroidImpl", "PermissionsAndroid", 
    "ReactNativeVersion", "ShareModule", "ToastAndroid", 
    "useAnimatedValue", "useAnimatedValueXY", "useAnimatedColor", "useColorScheme", 
    "Vibration", "extractOrigin",
    "Platform", "allocate", "isEnabled", "requireModule", "enableNativeCSSParsing", 
    "createGetter", "hue2rgb", "getIteratorFn", "attachDefaultEventTypes", 
    "isFabricReactTag", "raiseSoftError", 
    "getScaledAssetPath", "getAndroidAssetSuffix", "processEventTypes", 
    "composeIndexers", "polyfillObjectProperty", "castToNumber", 
    "getNodeFromInternalInstanceHandle", "focusInput", "defaultDiffer", 
    "rawToPerformanceEntryType", "isNativeFunction", "validateCallback", 
    "isDataView", "registerComponent", "ActivityIndicator", "isFabric", 
    "Background", "roundTo", "swizzle", "isArrayish", "executeNativeBackPress", 
    "enableFreeze", "RNSModule", "DelayedFreeze", "Suspender", 
    "isIndexInClosedRange", "parseUndefinedPropsToSystemDefault", 
    "getPositioningStyle", "getNativeEdgesProp", "FullWindowOverlay", 
    "RNSFullWindowOverlay", "bottomTabsDebugLog", "mapAppearanceToNativeProp", 
    "useIsKeyboardShown", "typeOf", "uuidv4", "base64Decode", "encodeFilename", 
    "validateBaseUrl", "pd", "v1", "v4", "v5", "v6", "v3", "rng", "unsafeStringify", 
    "validate", "stringToBytes", "md5ToHexEncodedArray", "f", "version", 
    "uint32ToUint8", "updateV1State", "updateV7State",
    "addCode", "ReactNativeBlobUtilSession", "ReactNativeBlobUtil", 
    "ReactNativeBlobUtilWriteStream", "ReactNativeBlobUtilReadStream", 
    "ReactNativeBlobUtilFile", "Log", "EventTarget", "readArrayBuffer", 
    "presentOptionsMenu", "OboeExtended", "canReadWriteToLegacyAndroidStorage", 
    "toSerializable", "debounce", "customAlphabet", "RNSVGCircle", "RNSVGClipPath", 
    "RNSVGDefs", "RNSVGEllipse", "RNSVGForeignObject", "RNSVGGroup", 
    "RNSVGLinearGradient", "RNSVGLine", "RNSVGMarker", "RNSVGMask", "RNSVGPath", 
    "RNSVGPattern", "RNSVGRadialGradient", "RNSVGRect", "RNSVGSvgViewAndroid", 
    "RNSVGSvgView", "RNSVGSymbol", "RNSVGText", "RNSVGTextPath", "RNSVGTSpan", 
    "RNSVGUse", "RNSVGFilter", "RNSVGFeBlend", "RNSVGFeColorMatrix", 
    "RNSVGFeComposite", "RNSVGFeFlood", "RNSVGFeGaussianBlur", "RNSVGFeMerge", 
    "RNSVGFeOffset", "RNSVGRenderableModule", "RNSVGSvgViewModule", "showErrorCSS", 
    "pickNotNil", "Mixin", "extractBrush", "extractFill", "extractOpacity", 
    "extractStroke", "extractLengthList", "extractResponder", 
    "extractSingleFontFamily", "extractViewBox", "extractPolyPoints", 
    "extractFeFlood", "parsePercentageRGBColor", "propsAndStyles", 
    "appendTransformProps", "append", "peg$SyntaxError", "peg$padEnd", 
    "percentToFloat", "Provider", 
    "equal", "createExporter", "hasDirectives", "symbolObservablePonyfill", 
    "maybe", "getEnterLeaveForKind", "isNode", "devAssert", "formatValue", 
    "isUnicodeScalarValue", "isDigit", "syntaxError", "getLocation", "isObjectLike", 
    "printSourceLocation", "leadingWhitespace", "isSource", 
    "isExecutableDefinitionNode", "getTokenDesc", "join", "escapedReplacer", 
    "findSchemaChanges", "isType", "identityFunc", "assertName", 
    "valueFromASTUntyped", "keyValMap", "toObjMap", "mapValue", "keyMap", 
    "stringToArray", "didYouMean", "serializeObject", "astFromValue", 
    "isIterableObject", "sortValueNode", "getFieldDef", "typeFromAST", 
    "isIntrospectionType", "isValidNameError", "buildASTSchema", "validateSDL", 
    "frozen", "MaxIntrospectionDepthRule", "ExecutableDefinitionsRule", 
    "UniqueOperationNamesRule", "LoneAnonymousOperationRule", 
    "SingleFieldSubscriptionsRule", "FragmentsOnCompositeTypesRule", 
    "VariablesAreInputTypesRule", "ScalarLeafsRule", "UniqueFragmentNamesRule", 
    "KnownFragmentNamesRule", "NoUnusedFragmentsRule", "NoFragmentCyclesRule", 
    "UniqueVariableNamesRule", "NoUndefinedVariablesRule", "NoUnusedVariablesRule", 
    "UniqueDirectivesPerLocationRule", "KnownArgumentNamesOnDirectivesRule", 
    "UniqueArgumentNamesRule", "ProvidedRequiredArgumentsOnDirectivesRule", 
    "UniqueInputFieldNamesRule", "LoneSchemaDefinitionRule", 
    "UniqueOperationTypesRule", "UniqueTypeNamesRule", "UniqueEnumValueNamesRule", 
    "UniqueArgumentDefinitionNamesRule", "UniqueDirectiveNamesRule", 
    "NoDeprecatedCustomRule", "NoSchemaIntrospectionCustomRule", 
    "collectFieldsImpl", "coerceVariableValues", "valueFromAST", "defaultOnError", 
    "printPathArray", "addPath", "isDirective", "isSDLNode", 
    "getSuggestedTypeNames", "getFragmentType", "isEqualType", "groupBy", 
    "getDirectiveLocationForASTPath", "isValidValueNode", "allowedVariableUsage", 
    "reasonMessage", "hasField", "typeToExtKind", "validateSchema", "isSchema", 
    "extendSchemaImpl", "buildClientSchema", "concatAST", "getIntrospectionQuery", 
    "getOperationAST", "getOperationRootType", "introspectionFromSchema", 
    "execute", "memoize3", "isPromise", "promiseReduce", "promiseForObject", 
    "isLocatedGraphQLError", "sortObjMap", "isDefinedType", 
    "collectTransitiveDependencies", "stripIgnoredCharacters", "isAsyncIterable", 
    "mapAsyncIterator", "graphqlImpl", "defaultDispose$1", "isObjRef", 
    "maybeUnsubscribe", "generateErrorMessage", "warnOnImproperCacheImplementation", 
    "isMuted", "createOperation", "asyncIterator", "normalize", "getApolloContext", 
    "setContext", "initializeSentry", "ignoreNextOnError", "parseBaggageHeader", 
    "isBuiltin", "consoleSandbox", "getGlobalSingleton", "combined", 
    "isValidProtocol", "getBaseApiEndpoint", "getFirstException", 
    "isMatchingPattern", "addNonEnumerableProperty", "updateSession", 
    "rejectedSyncPromise", "SyncPromise", "dateTimestampInSeconds", 
    "filterDuplicates", "getCurrentScope", "getSentryCarrier", 
    "getAsyncContextStrategy", "getAsyncContextStack", "ScopeClass", 
    "generateTraceId", "getDefaultCurrentScope", "enhanceEventWithSdkInfo", 
    "forEachEnvelopeItem", "memoBuilder", "createStackParser", 
    "getDynamicSamplingContextFromClient", "spanTimeInputToSeconds", 
    "extractTraceparentData", "getMetricSummaryJsonForSpan", 
    "getSpanStatusFromHttpCode", "hasTracingEnabled", "applyClientOptions", 
    "mergeAndOverwriteScopeData", "notifyEventProcessors", 
    "getFilenameToDebugIdMap", "parseSampleRate", "createClientReportEnvelope", 
    "BrowserMetricsAggregator", "MetricsAggregator", "sanitizeTagKey", 
    "CounterMetric", "createMetricEnvelope", "parseRetryAfterHeader", 
    "extractUserData", "getNumberOfUrlSegments", "parseForwardedHeader", 
    "parseCookie", "LRUMap", "SentryNonRecordingSpan", "isSpanTimeInput", 
    "logSpanEnd", "setMeasurement", "getCapturedScopesOnSpan", "errorCallback", 
    "instrumentError", "addHandler", "instrumentUnhandledRejection", 
    "parseStackFrames", "SessionFlusher", "createCheckInEnvelopeItem", 
    "withActiveSpan", "maybeHandlePromiseRejection", "sampleSpan", "addBreadcrumb", 
    "instrumentConsole", "captureCheckIn", "instrumentFetch", "supportsFetch", 
    "addTracingExtensions", "scopeToTraceHeader", "aggregateExceptionsFromError", 
    "applySdkMetadata", "normalizeArray", "callFrameToStackFrame", 
    "filenameIsInApp", "consoleHandler", "severityLevelFromString", 
    "captureFeedback", "getEventForEnvelopeItem", "makePromiseBuffer", 
    "dynamicRequire", "getSDKSource", "escapeStringForRegex", "flatten", 
    "getBreadcrumbLogLevelFromHttpStatusCode", "getCurrentHubShim", 
    "getTraceMetaTags", "setCurrentClient", "isElectronNodeRenderer", 
    "checkTunnel", "makeFifoCache", "eventFromEnvelope", "makeOfflineTransport", 
    "getMetricsAggregatorForClient", "ensureMetadataStacksAreParsed", 
    "parameterize", "isProfilingIntegrationWithProfiler", 
    "convertReqDataIntegrationOptsToAddReqDataOpts", "generateIteratee", 
    "supportsHistory", "getBundleKeysForAllFramesWithFilenames", "captureIfError", 
    "vercelWaitUntil", "originalExceptionIsZodError", "exceptionFromError", 
    "createUserFeedbackEnvelopeItem", "OpenFeatureIntegrationHook", 
    "insertToFlagBuffer", "instrumentXHR", "instrumentDOM", "triggerHandlers", 
    "onCLS", "onFCP", "onFID", "onLCP", "onINP", "whenActivated", 
    "initHiddenTime", "initMetric", "getNavigationEntry", "getActivationStart", 
    "generateUniqueID", "observe", "getRating", "runOnce", "onHidden", 
    "whenIdle", "whenReady", "updateEstimate", "getInteractionCountForNavigation", 
    "instrumentHistory", "extractNetworkProtocol", "sendStandaloneClsSpan", 
    "getNativeImplementation", "isProcessedJSSelfProfile", "startProfileForSpan", 
    "startBrowserTracingPageLoadSpan", "isPerformanceResourceTiming", 
    "registerBackgroundTabDetection", "buildLaunchDarklyFlagUsedHandler", 
    "getDefaultIntegrations", "createFrame", "makeFetchTransport", 
    "addSourceContext", "isScreenshotSupported", "promisifyRequest", 
    "elementClassMatchesRegex", "setupSidecarForwarding", "isAtLeastReact17", 
    "createReduxEnhancer", "init", "normalizeTransactionName", 
    "instrumentReactRouter", "wrapUseRoutesV6", "handleNavigation", 
    "reactRouterV7BrowserTracingIntegration", "routeMatchToParamSpanAttributes", 
    "lazyLoadAutoInjectFeedbackButtonIntegration", "getTheme", 
    "defaultButtonStyles", "isMobileOs", "getDevServer", "getExpoConstants", 
    "isModalSupported", "getRNSentryModule", "tripletToBase64", "utf8ToBytes", 
    "isHardCrash", "convertToNormalizedObject", "warnMessage", 
    "ignoreRequireCycleLogs", "mergeOutcomes", "createStealthXhr", 
    "getSentryMetroSourceContextUrl", "mergeOptions", "hasHooks", 
    "getDefaultTracePropagationTargets", "getDefaultIdleNavigationSpanOptions", 
    "convertSpanToTransaction", "onThisSpanEnd", "appRegistryIntegration", 
    "fillTyped", "setSpanMeasurement", "createIntegration", 
    "reactNativeNavigationIntegration", "getReactNavigationIntegration", 
    "AsyncExpiringMap", "addGestureBreadcrumb", "userInteractionIntegration", 
    "enableSyncToNative", "breadcrumbFromObject", "safeFactory", 
    "shouldEnableNativeNagger", "browserReplayIntegration", "fetchNativeFrames", 
    "createReactNativeRewriteFrames", "processEvent", "createSyntheticError", 
    "eventOriginIntegration", "getExpoUpdatesContext", "startProfiling", 
    "isValidProfile", "getDebugMetadata", "mapSamples", "createProcessEvent", 
    "setup", "getPromisePolyfill", "done", "disable", "stallTrackingIntegration", 
    "addTimeToInitialDisplay", "loadOrganizationRegistry", "Link", 
    "getPartialState", "useNavigationIndependentTree", "useSyncState", 
    "isPlainObject", "useChildListeners", "useKeyedChildListeners", 
    "createNavigationContainerRef", "DrawerRouter", "TabRouter", "StackRouter", 
    "goBack", "findFocusedRoute", "useEventEmitter", "useOptionsGetters", 
    "EnsureSingleNavigator", "ThemeProvider", "ThemeContext", 
    "NavigationIndependentTree", "PreventRemoveProvider", 
    "createComponentForStaticNavigation", "createNavigatorFactory", "Screen", 
    "Group", "getActionFromState", "getFocusedRouteNameFromRoute", "useRouteCache", 
    "isRecordEqual", "getPathFromState", "encoderForArrayFormat", 
    "decodeComponents", "validatePathConfig", "getPatternParts", 
    "getConfigResources", "isArrayEqual", "arrayStartsWith", "useFocusEffect", 
    "useNavigation", "useIsFocused", "useNavigationBuilder", 
    "useRegisterNavigator", "useLazyValue", "useScheduleUpdate", "useFocusEvents", 
    "useOnAction", "useOnPreventRemove", "useOnRouteFocus", "useNavigationHelpers", 
    "useFocusedListenersChildrenAdapter", "useOnGetState", "useNavigationCache", 
    "SceneView", "useCurrentRender", "useComponent", 
    "NavigationStateListenerProvider", "useNavigationContainerRef", 
    "usePreventRemove", "usePreventRemoveContext", "useStateForPath", "useTheme", 
    "useLinkProps", "LocaleDirContext", "useBackButton", "useDocumentTitle", 
    "useLinking", "extractPathFromURL", "useThenable", "createStaticNavigation", 
    "useLinkBuilder", "useLinkTo", "useLocale", "useRoutePath", "getScrollableNode", 
    "useLatestRef", "HeaderBackButton", "HeaderIcon", "HeaderTitle", 
    "HeaderBackground", "Label", "MissingIcon", "ResourceSavingView", 
    "SafeAreaProviderCompat", "getHeaderTitle", "getLabel", "useHeaderHeight", 
    "useHeaderConfigProps", "RNSScreenStackHeaderConfig", 
    "RNSScreenStackHeaderSubview", "RNSScreen", "RNSModalScreen", "RNSSearchBar", 
    "ScreenContainer", "RNSScreenContainer", "RNSScreenNavigationContainer", 
    "RNSScreenStack", "ScreenContentWrapper", "RNSScreenContentWrapper", 
    "RNSSafeAreaView", "ScreenFooter", "RNSScreenFooter", "useTransitionProgress", 
    "TabsHost", "RNSBottomTabs", "TabsAccessory", "RNSBottomTabsAccessory", 
    "TabsAccessoryContent", "RNSBottomTabsAccessoryContent", 
    "useAnimatedHeaderHeight", "useDismissedRouteError", 
    "useInvalidPreventRemoveError", "getModalRouteKeys", "NativeStackNavigator", 
    "NavigationHeaderLeft", "NavigationHeaderRight", "NavigationShareButton", 
    "BottomTabBar", "BottomTabItem", "TabBarIcon", "BottomTabView", "forFade", 
    "useAnimatedHashMap", "MaybeScreen", "BottomTabNavigator", 
    "useBottomTabBarHeight", "Events", "useAsyncStorage", 
    "shouldFallbackToLegacyNativeModule", "convertError",
    "FlushPolicyExecuter", "warnIfMissingPackage", 
    "registerBridgeStore", "canScheduleExactAlarms", "proxifyPermissions", 
    "RNPermissions", "getUnsupportedError", "RNCSafeAreaProvider", 
    "RNCSafeAreaView", "RNCSafeAreaContext", "use", "items", "items1", "keys1", 
    "keys2", "keys3", "keys4", "keys5", "atomResult1", "forwardRefResult1", 
    "z", "t", "A", 
    "Text", "Button", "Modal", "Header", "jsxProd", "SvgComponent", "MaskedView",
    "Spinner", "Badge", "ButtonLink", "IconButton", "LightLogo",
    "useState", "useEffect", "useRef", "useMemo", "useCallback", "useLayoutEffect",
    "usePrevious", "useMounted",
    "useRoute", "useAppNavigation", "useScreenOptions", "useScreenTracking",
    "RootNavigationScreen",
    "atomFamily", "atomTree", "isWritableAtom", "mountAtom", "ensureAtomEffectChannel",
    "push", "isEqual", "assert", "getUUID",
    "normalizePhoneNumber", "formatDuration",
    "isNumber", "isNonNullObject", "s4",
    "noop", "apply", "getContext", "getNamedContext",
    "RNCSafeAreaProvider", "RNCSafeAreaView", "RNSScreenContentWrapper", "RNSScreenStack", "ScreenContentWrapper"
]

REMOVE_NAMES_SET = set(REMOVE_MODULE_NAMES)

def purge_bundle_by_name(input_path, output_path):
    if not os.path.exists(input_path):
        sys.exit(1)

    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()

    pattern = re.compile(r'(// === Module \d+:\s*(.*?)\s*===.*?)(?=(?:// === Module \d+:)|$)', re.DOTALL)
    
    modified_content = content
    offset = 0
    
    for match in pattern.finditer(content):
        full_block = match.group(1)
        module_name = match.group(2).strip()
        
        if module_name in REMOVE_NAMES_SET or module_name.startswith('_'):
            start_idx = match.start() + offset
            end_idx = match.end() + offset
            
            replacement = ""
            modified_content = modified_content[:start_idx] + replacement + modified_content[end_idx:]
            offset += len(replacement) - len(full_block)
            
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(modified_content)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python clean.py <input_file> <output_file>", file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    purge_bundle_by_name(input_file, output_file)